spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/adwp_work1
      username: root
      password: root
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb